### PR TITLE
PR for SRVLOGIC-83: [DOC] Remove "Kogito" name from Serverless Logic documents

### PR DESCRIPTION
**Pull request by kaldesai**
Tracking JIRA: https://issues.redhat.com/browse/SRVLOGIC-83

Doc preview: [Function accessing contextual data](https://deploy-preview-100--jazzy-shortbread-5f62b7.netlify.app/docs/latest/serverless-logic/core/custom-functions-support#_function_accessing_contextual_data)

Required reviews from @krisv and @ricardozanini

### CODE REVIEW

**Review by krisv — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by MarianMacik — COMMENTED** [review]
@kaldesai Is this PR complete? By looking at the jira it should remove Kogito references. But for example there is still `Kogito Serverless Workflow Visualization` feature mentioned in the docs.

**Comment by kaldesai** [comment]
@MarianMacik 

**Kogito Serverless Workflow Visualization** is a UI element. It is a checkbox. So I kept it as it is. 
I am attaching the following screenshot of the same: 
image

If we can change the name over there I will update it in the docs. 

@krisv @ricardozanini Can you please verify?

**Comment by MarianMacik** [comment]
@kaldesai Just found one more thing which might be good to rename perhaps:

https://github.com/openshift-knative/docs/blob/4aad4334d33e4ef4a0946b182c5d864338006427/modules/serverless-logic/pages/core/custom-functions-support.adoc#L577

Everything else is either UI-related or there are example outputs or it is a name of an addon (Kogito Knative Eventing add-on), where it doesn't make sense to rename it, it would only cause more confusion. Looks good to me otherwise.

**Comment by ricardozanini** [comment]
@kaldesai since 1.30 is out we can merge this. However, we also need to cherry-pick everything from 1.40.x branch here: https://github.com/apache/incubator-kie-kogito-docs/tree/1.40.x-prod

**Comment by kaldesai** [comment]
> @kaldesai Just found one more thing which might be good to rename perhaps:
> 
> https://github.com/openshift-knative/docs/blob/4aad4334d33e4ef4a0946b182c5d864338006427/modules/serverless-logic/pages/core/custom-functions-support.adoc#L577
> 
> Everything else is either UI-related or there are example outputs or it is a name of an addon (Kogito Knative Eventing add-on), where it doesn't make sense to rename it, it would only cause more confusion. Looks good to me otherwise.

@MarianMacik I have incorporated your suggestion and renamed it.

**Review by MarianMacik — APPROVED** [review]
Looks good now, thanks @kaldesai!

**Pull request merged**
